[package]
name = "jupiter-kusama"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"
description = ""

[dependencies]
cli = { package = "polkadot-cli", path = "cli" }

[target.'cfg(target_arch="x86_64")'.dependencies]
cli = { package = "polkadot-cli", path = "cli", features = [ "wasmtime" ] }

[features]
runtime-benchmarks=["cli/runtime-benchmarks"]
