[package]
name = "jupiter-para-cli"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"
serde_json = "1.0"
hex-literal = "0.2.1"
codec = { package = 'parity-scale-codec', version = '1.0.0' }
ansi_term = "0.12.1"
serde = { version = "1.0.101", features = ["derive"] }

# Substrate dependencies
sc-authority-discovery = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-basic-authorship = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-transaction-pool = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-network = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-aura = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-finality-grandpa = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-client-api = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-rpc = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-informant = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

sp-core = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-inherents = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-transaction-pool = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-consensus-aura = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-consensus = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-finality-grandpa = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-runtime = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }
sc-executor = { version = "0.8.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-benchmarking = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

pallet-contracts = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

jupiter-primitives = { path = "../../../primitives" }
jupiter-para-runtime = { path = "../../../runtime/jupiter-para" }
jupiter-rpc = { path = "../../../rpc" }

# Cumulus dependencies
cumulus-consensus = { git = "https://github.com/paritytech/cumulus"}
cumulus-collator = { git = "https://github.com/paritytech/cumulus"}
cumulus-network = { git = "https://github.com/paritytech/cumulus"}
cumulus-primitives = { git = "https://github.com/paritytech/cumulus"}
cumulus-service = { git = "https://github.com/paritytech/cumulus"}

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }
polkadot-collator = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0-rc5", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

[features]
default = ["cli"]
cli = [
    "sc-cli",
    "sc-service",
    "sc-executor/wasmi-errno",
]
wasmtime = [
    "sc-cli/wasmtime",
    "sc-service/wasmtime",
    "sc-executor/wasmtime",
]
