[package]
name = "jupiter-para-cli"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"
serde_json = "1.0"
hex-literal = "0.2.1"

sc-authority-discovery = { version = "0.8.0" }
sc-basic-authorship = { version = "0.8.0" }
sc-transaction-pool = { version = "2.0.0" }
sc-network = { version = "0.8.0" }
sc-consensus-aura = { version = "0.8.0" }
sc-consensus = { version = "0.8.0" }
sc-finality-grandpa = { version = "0.8.0" }
sc-client-api = { version = "2.0.0" }
sc-rpc = { version = "2.0.0" }

sp-core = { version = "2.0.0" }
sp-inherents = { version = "2.0.0" }
sp-transaction-pool = { version = "2.0.0" }
sp-consensus-aura = { version = "0.8.0" }
sp-consensus = { version = "0.8.0" }
sp-finality-grandpa = { version = "2.0.0" }
sp-runtime = { version = "2.0.0" }

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }
sc-executor = { version = "0.8.0" }
frame-benchmarking = { version = "2.0.0" }

pallet-contracts = { version = "2.0.0" }

jupiter-primitives = { path = "../../../primitives" }
jupiter-para-runtime = { path = "../../../runtime/jupiter-para" }
jupiter-rpc = { path = "../../../rpc" }

polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-branch" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0" }

[features]
default = ["cli"]
cli = [
    "sc-cli",
    "sc-service",
    "sc-executor/wasmi-errno",
]
wasmtime = [
    "sc-cli/wasmtime",
    "sc-service/wasmtime",
    "sc-executor/wasmtime",
]
