[workspace]
members = [
    "bin/node-pure",
    "bin/node-pure/executor",
    "bin/node-dev",
    "bin/node-para",
    "frame/contracts-ext",
    "runtime/jupiter-dev",
    "runtime/jupiter-para",
    "runtime/jupiter-pure",
    "primitives",
    "primitives/io",
    "rpc",
]
exclude = ["vendor/substrate"]

[profile.release]
panic = "unwind"

