[package]
name = "polkadot-cli"
version = "0.8.26"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot Relay-chain Client Node"
edition = "2018"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = "1.0.22"
hex-literal = "0.3.1"
structopt = { version = "0.3.20", optional = true }
futures = { version = "0.3.1", features = ["compat"] }
codec = { package = "parity-scale-codec", version = "1.3.4" }
serde = { version = "1.0.117", features = ["derive"] }
wasm-bindgen = { version = "0.2.68", optional = true }
wasm-bindgen-futures = { version = "0.4.18", optional = true }

tracing-futures = "0.2.4"
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "master" }
browser-utils = { package = "substrate-browser-utils", git = "https://github.com/paritytech/substrate", branch = "master", optional = true }

sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "master" }

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
sc-client-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-slots = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-babe = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-authority-discovery = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-basic-authorship = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "master" }

# Substrate Primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "master" }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "master" }
#consensus_common = { package = "sp-consensus", git = "https://github.com/paritytech/substrate", branch = "master" }
grandpa_primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }

# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/paritytech/substrate/pull/6745
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "master" }

# Substrate Pallets
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "master" }

primitives = { package = "jupiter-primitives", path = "../../../primitives" }
jupiter-kusama-runtime = { path = "../../../runtime/jupiter-kusama" }
polkadot-rpc = { path = "../rpc" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = [ "wasmtime", "cli", "trie-memory-tracker" ]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
	"structopt",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
browser = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"browser-utils",
]
trie-memory-tracker = [ "sp-trie/memory-tracker" ]
runtime-benchmarks = []
